### ISSUE TITLE
Preview Button not showing up

### ISSUE THREAD

**Issue by Choder7** [dohyeon5626/github-html-preview-extension#20]
Preview Button isn't showing up sometimes, after not appearing it doesn't appear anymore even after reinstalling extension or reloading page.

Maybe it is caused when having multiple windows with html code in GitHub open?

**Comment by dohyeon5626** [comment]
@Choder7 
Thank you for reporting this issue. I have confirmed that the selectors of elements on the GitHub web have changed, preventing the button from being created. I will fix this issue and release an update. Thank you!

**Comment by dohyeon5626** [comment]
@Choder7 
The issue has been fixed and version 3.2 has been released. Thank you.
